log_level: INFO
prometheus_port: 9102
device_information:
    hosts: 10.114.250.71,10.114.250.73,10.114.250.75,10.114.250.7,10.114.250.9
    username:
    password:
    tenant_name: cc-openstack-eu-de-1
    proxy: 
        http: ''
        https: ''
        no_proxy: '*'
exporter_types:
    apichealth:
      name: apichealth
      enabled: True
      collection_interval: 60