device_information:
    hostname: localhost
    username: admin2
    password: password
    tenant_name: sometenant
    proxy: 
        http: ''
        https: ''
        no: '*'
    log_level: INFO
exporter_types:
    apichealth:
        enabled: True
        collection_interval: 60
        prometheus_port: 9102