device_information:
  hostname: vc.test.local
  username: administrator@vsphere.local
  password: password
  port: 443
  ignore_ssl: true
  log_level: INFO
exporter_types:
  vcapiandversions:
    enabled: True
    collection_interval: 120
    prometheus_port: 9102
  vccustomervmmetrics:
    enabled: False
    collection_interval: 120
    prometheus_port: 9102
    shorter_names_regex: '\.some\.domain\.name'
    host_match_regex: '.*buildingblock-xy.*'
    ignore_match_regex: '^testvmware.*'
    vm_metrics:
    - 'cpu.latency.average'
    - 'cpu.usage.average'
    - 'cpu.usagemhz.average'
    - 'cpu.wait.summation'
    - 'disk.usage.average'
    - 'disk.numberRead.summation'
    - 'disk.numberWrite.summation'
    - 'mem.usage.average'
    - 'net.usage.average'
    - 'net.bytesRx.average'
    - 'net.bytesTx.average'
    - 'net.droppedRx.summation'
    - 'net.droppedTx.summation'
    - 'net.errorsRx.summation'
    - 'net.errorsTx.summation'
    - 'net.packetsRx.summation'
    - 'net.packetsTx.summation'
    - 'virtualDisk.read.average'
    - 'virtualDisk.write.average'
    - 'virtualDisk.readIOI.latest'
    - 'virtualDisk.writeIOI.latest'
    - 'virtualDisk.totalReadLatency.average'
    - 'virtualDisk.totalWriteLatency.average'
  customerdsmetrics:
    enabled: False
    collection_interval: 120
    prometheus_port: 9102
