log_level: DEBUG
prometheus_port: 9102
device_information:
  hostname: vc.test.local
  username: administrator@vsphere.local
  # note: this is the masterpassword to generate the actual pw
  password: masterpassword
  port: 443
  ignore_ssl: true
exporter_types:
  vchostmetrics:
    name: vchostmetrics
    enabled: True
    collection_interval: 120
  vcapiandversions:
    name: vcapiandversions
    enabled: True
    collection_interval: 120
  vccustomerdsmetrics:
    name: vccustomerdsmetrics
    enabled: True
    collection_interval: 120
    ignore_ds_match_regex: '(^.*Management.*$|.*local$)'
  vccustomervmmetrics:
    name: vccustomervmmetrics
    enabled: True
    collection_interval: 120
    shorter_names_regex: '\.some\.domain\.name'
    host_match_regex: '.*buildingblock-xy.*'
    ignore_vm_match_regex: '^testvmware.*'
    vm_metrics:
    - 'cpu.latency.average'
    - 'cpu.usage.average'
    - 'cpu.usagemhz.average'
    - 'cpu.wait.summation'
    - 'disk.usage.average'
    - 'disk.numberRead.summation'
    - 'disk.numberWrite.summation'
    - 'mem.usage.average'
    - 'net.usage.average'
    - 'net.bytesRx.average'
    - 'net.bytesTx.average'
    - 'net.droppedRx.summation'
    - 'net.droppedTx.summation'
    - 'net.errorsRx.summation'
    - 'net.errorsTx.summation'
    - 'net.packetsRx.summation'
    - 'net.packetsTx.summation'
    - 'virtualDisk.read.average'
    - 'virtualDisk.write.average'
    - 'virtualDisk.readIOI.latest'
    - 'virtualDisk.writeIOI.latest'
    - 'virtualDisk.totalReadLatency.average'
    - 'virtualDisk.totalWriteLatency.average'
